version: "3.1"
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/projet-GLO-4035
    depends_on:
      - mongo
      - neo4j

  mongo:
    image: mongo
  neo4j:
    image: neo4j