version: '2'
services:
    web:
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/code
        depends_on:
            - mongo
            - neo4j

    mongo:
        image: mongo
    neo4j:
        image: neo4j
